# Generated by Django 3.2.4 on 2021-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210826_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='user2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=60)),
                ('phone_no', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
