# Generated by Django 3.2.4 on 2021-09-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user2',
            old_name='username',
            new_name='full_name',
        ),
    ]
