# Generated by Django 3.2.4 on 2021-09-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_rename_username_user2_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user2',
            new_name='guser',
        ),
    ]
