# Generated by Django 3.2.4 on 2021-09-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_rename_user2_guser'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField()),
                ('faculties', models.JSONField()),
                ('image1', models.ImageField(blank=True, upload_to='hotel_image/')),
                ('image2', models.ImageField(blank=True, upload_to='hotel_image/')),
                ('image3', models.ImageField(blank=True, upload_to='hotel_image/')),
                ('image4', models.ImageField(blank=True, upload_to='hotel_image/')),
                ('image5', models.ImageField(blank=True, upload_to='hotel_image/')),
            ],
        ),
    ]
