# Generated by Django 3.2.4 on 2021-09-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField()),
                ('food_type', models.JSONField()),
                ('image1', models.ImageField(blank=True, upload_to='venue_image/')),
                ('image2', models.ImageField(blank=True, upload_to='venue_image/')),
                ('image3', models.ImageField(blank=True, upload_to='venue_image/')),
                ('image4', models.ImageField(blank=True, upload_to='venue_image/')),
                ('image5', models.ImageField(blank=True, upload_to='venue_image/')),
            ],
        ),
    ]
